name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: ⬢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          cache: npm

      - name: 📦 Install Packages
        run: npm ci

      - name: 🏗 Build
        run: npm run build

      - name: 🚀 Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
