name: Stale
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  issues: write # to close stale issues (actions/stale)
  pull-requests: write # to close stale PRs (actions/stale)

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    steps:
      - name: 🧹 Clean stale issues and pull requests
        uses: actions/stale@v10
        with:
          stale-issue-message: >
            There hasn't been any activity on this issue recently.
            This issue has now been marked as stale and will be closed if no further activity occurs.
            Please, update to the latest version and check if that solves the issue.

            Thank you for your contributions!
          close-issue-message: >
            This issue was closed because it has been stalled for 30 days with no activity.
            Please open a new issue if the issue is still relevant, linking to this one.
          stale-pr-message: >
            This PR is stale because there hasn't been any activity for a long time.
          close-pr-message: >
            This PR was closed because it has been stalled for 30 days with no activity.
          days-before-issue-stale: 60
          days-before-pr-stale: 90
          days-before-issue-close: 30
          days-before-pr-close: 30
          exempt-all-milestones: true
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: no-stale
          exempt-pr-labels: no-stale
          exempt-draft-pr: true
